"""End-to-end check of the bundled New Horizons MVIC sample.

Drive ``picmaker`` with the sample versions file and the base options that the
``NHxxMV_previews.sh`` script applies, then compare each generated preview
against the committed reference image, reading the source data both from the
PDS3 label (``.lbl``) and from the FITS image (``.fit``) directly.

MVIC frames are long strips, so every preview here exercises the wrapping
layout (``--wrap`` / ``--overlaps`` / ``--wrap-ratio``) along with gamma,
valid-range masking, cropping, padding and the instrument tint.
"""

from pathlib import Path

import pytest

from tests import assert_preview_matches, generate_previews

DATA_DIR = Path(__file__).parent.parent / 'test_files' / 'nh_mvic'
VERSIONS_FILE = DATA_DIR / 'NHxxMV_previews.txt'
LABEL = DATA_DIR / 'mc0_0299064592_0x545_sci.lbl'
IMAGE = DATA_DIR / 'mc0_0299064592_0x545_sci.fit'

# Base options the NHxxMV_previews.sh script applies to every version (the
# versions file itself lists only the per-preview overrides). The reference
# images were generated by the old tool, which inverted the gamma exponent,
# so the script's ``--gamma 2`` is reproduced here as ``--gamma 0.5``.
BASE_ARGS = ('--up', '--extension=jpg', '--valid', '0', '32767',
             '--percentiles', '0.1', '99.9', '--footprint=5', '--gamma', '0.5')

# Every preview the versions file produces for this image, each with a
# committed reference image of the same name.
PREVIEWS = (
    'mc0_0299064592_0x545_sci_full.jpg',
    'mc0_0299064592_0x545_sci_med.jpg',
    'mc0_0299064592_0x545_sci_small.jpg',
    'mc0_0299064592_0x545_sci_thumb.jpg',
)


@pytest.mark.parametrize('reader', ['label', 'fits'])
def test_nh_mvic_previews_match_references(reader: str, tmp_path: Path) -> None:
    """Each generated preview reproduces its reference image, whether the
    source is read from the PDS3 label or from the FITS image."""
    input_path = LABEL if reader == 'label' else IMAGE
    generate_previews(input_path, tmp_path, VERSIONS_FILE, extra_args=BASE_ARGS)

    for name in PREVIEWS:
        produced_path = tmp_path / name
        assert produced_path.exists(), f'{name} was not generated'
        assert_preview_matches(produced_path, DATA_DIR / name)
