"""Byte-identical pipeline-output snapshot tests.

For each (fixture, combo, ext) triple in `snapshots_index.SNAPSHOTS`, the
test re-runs `images_to_pics` and asserts that the produced bytes match
the snapshot committed under `tests/fixtures/expected/`. PR 3's
vectorization commits will run this same test and expect byte identity.

Snapshots are regenerated by `python tests/generate_snapshots.py`.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from picmaker.picmaker import images_to_pics

from snapshots_index import SNAPSHOTS


@pytest.mark.parametrize(('fixture', 'slug', 'ext'), SNAPSHOTS)
def test_byte_identical_snapshot(
    fixture: str, slug: str, ext: str, fixtures_dir: Path, tmp_path: Path
) -> None:
    expected = fixtures_dir / 'expected' / f'{Path(fixture).stem}--{slug}.{ext}'
    assert expected.exists(), f'missing snapshot fixture: {expected}'

    # Map slug → kwargs (keep in lockstep with generate_snapshots.COMBOS).
    kwargs: dict
    if slug == 'default':
        kwargs = {}
    elif slug == 'gamma2':
        kwargs = {'gamma': 2.0}
    elif slug == 'pct5_95':
        kwargs = {'percentiles': (5.0, 95.0)}
    elif slug == 'colormap_red_blue':
        kwargs = {'colormap': 'red-blue'}
    elif slug == 'tint':
        kwargs = {'tint': True}
    elif slug == 'rot90':
        kwargs = {'rotate': 'rot90'}
    elif slug == 'frame_128_pad':
        kwargs = {'frame': (128, 128), 'pad': True}
    elif slug == 'frame_max_50':
        kwargs = {'frame_max': 50}
    elif slug == 'twobytes_tiff':
        kwargs = {'twobytes': True}
    else:
        pytest.fail(f'unknown slug: {slug}')

    images_to_pics(
        [str(fixtures_dir / fixture)],
        directory=str(tmp_path),
        suffix=f'--{slug}',
        extension=ext,
        **kwargs,
    )
    produced = tmp_path / f'{Path(fixture).stem}--{slug}.{ext}'
    assert produced.exists()
    assert produced.read_bytes() == expected.read_bytes(), (
        f'snapshot drift for {expected.name}; regenerate via '
        f'tests/generate_snapshots.py if the change is intentional.'
    )
