"""Byte-identical pipeline-output snapshot tests.

For each (fixture, combo, ext) triple in `snapshots_index.SNAPSHOTS`, the
test re-runs `images_to_pics` and asserts that the produced bytes match
the snapshot committed under `tests/fixtures/expected/`. PR 3's
vectorization commits will run this same test and expect byte identity.

Snapshots are regenerated by `python tests/fixture_recipes/generate_snapshots.py`.
"""

from pathlib import Path

import pytest
from snapshots_index import KWARGS_BY_SLUG, SNAPSHOTS

from picmaker import images_to_pics


@pytest.mark.parametrize(('fixture', 'slug', 'ext'), SNAPSHOTS)
def test_byte_identical_snapshot(
    fixture: str, slug: str, ext: str, fixtures_dir: Path, tmp_path: Path
) -> None:
    expected = fixtures_dir / 'expected' / f'{Path(fixture).stem}--{slug}.{ext}'
    assert expected.exists(), f'missing snapshot fixture: {expected}'

    kwargs = KWARGS_BY_SLUG.get(slug)
    if kwargs is None:
        pytest.fail(f'unknown slug: {slug}')

    images_to_pics(
        [str(fixtures_dir / fixture)],
        directory=str(tmp_path),
        suffix=f'--{slug}',
        extension=ext,
        **kwargs,
    )
    produced = tmp_path / f'{Path(fixture).stem}--{slug}.{ext}'
    assert produced.exists()
    assert produced.read_bytes() == expected.read_bytes(), (
        f'snapshot drift for {expected.name}; regenerate via '
        f'tests/fixture_recipes/generate_snapshots.py if the change is intentional.'
    )
