"""Pipeline-output snapshot tests, compared by decoded pixels.

For each (fixture, combo, ext) triple in `snapshots_index.SNAPSHOTS`, the test
re-runs the pipeline and compares the produced image to the snapshot committed
under `tests/fixtures/expected/` — by *decoded pixels*, not raw file bytes.
The comparison reduces the per-pixel difference to its largest absolute value and
its RMS and fails if either exceeds a threshold. Lossless snapshots (PNG/TIFF) must
match exactly (thresholds 0); lossy JPEG snapshots must stay within a small
tolerance, so a future Pillow/libjpeg revision that shifts a few DN does not break
the suite while real pipeline regressions still do. The generator and this test
share `tests.render_snapshot`, so their invocations are identical.

Snapshots are regenerated by `python tests/fixture_recipes/generate_snapshots.py`.
"""

from pathlib import Path

import pytest

from tests import assert_snapshot_matches, render_snapshot
from tests.snapshots_index import KWARGS_BY_SLUG, SNAPSHOTS


@pytest.mark.parametrize(('fixture', 'slug', 'ext'), SNAPSHOTS)
def test_snapshot_pixels_match(
    fixture: str, slug: str, ext: str, fixtures_dir: Path, tmp_path: Path
) -> None:
    expected = fixtures_dir / 'expected' / f'{Path(fixture).stem}--{slug}.{ext}'
    assert expected.exists(), f'missing snapshot fixture: {expected}'

    kwargs = KWARGS_BY_SLUG.get(slug)
    if kwargs is None:
        pytest.fail(f'unknown slug: {slug}')

    render_snapshot(fixtures_dir / fixture, tmp_path, slug, kwargs, ext)
    produced = tmp_path / f'{Path(fixture).stem}--{slug}.{ext}'
    assert produced.exists()
    assert_snapshot_matches(produced, expected, ext)
