"""Generate byte-identical snapshots of the unvectorized pipeline output.

These snapshots are the baseline that PR 3's vectorization assertion diffs
against. Run from the repo root inside the project venv:

    python tests/fixture_recipes/generate_snapshots.py

The script:
- Iterates a hardcoded list of `(fixture, combo, output_ext)` triples,
  pre-filtered to drop combos that don't make sense for the fixture
  (e.g. `--hst` for non-HST images).
- Reads each input from `tests/fixtures/<name>` and writes the produced
  snapshot to `tests/fixtures/expected/`.
- Logs each generation as success/failure; failures are removed from the
  emitted `snapshots_index.py` parametrize list so the test suite stays
  in sync with the actual produced fixtures.
- Emits the surviving list to `tests/snapshots_index.py` (sits next to
  `test_snapshots.py` which imports it directly).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from picmaker.picmaker import images_to_pics

HERE = Path(__file__).parent
FIXTURES = HERE.parent / 'fixtures'
EXPECTED = FIXTURES / 'expected'
SNAPSHOTS_INDEX = HERE.parent / 'snapshots_index.py'

VICAR_FIXTURES = ['cassini_iss.vic', 'voyager_iss.vic', 'galileo_ssi_a.vic']
FITS_FIXTURES = ['hst_wfc3.fits', 'hst_acs.fits', 'hst_wfpc2.fits', 'nh_mvic.fits']
ALL_FIXTURES = VICAR_FIXTURES + FITS_FIXTURES

# Each combo is (slug, kwargs, extension). The slug becomes part of the
# output filename; kwargs are passed through to images_to_pics.
COMBOS: list[tuple[str, dict[str, Any], str]] = [
    ('default', {}, 'jpg'),
    ('gamma2', {'gamma': 2.0}, 'jpg'),
    ('pct5_95', {'percentiles': (5.0, 95.0)}, 'jpg'),
    ('colormap_red_blue', {'colormap': 'red-blue'}, 'jpg'),
    ('tint', {'tint': True}, 'jpg'),
    ('rot90', {'rotate': 'rot90'}, 'jpg'),
    ('frame_128_pad', {'frame': (128, 128), 'pad': True}, 'jpg'),
    ('frame_max_50', {'frame_max': 50}, 'jpg'),
    ('twobytes_tiff', {'twobytes': True}, 'tiff'),
]


def _safe_name(fixture: str, slug: str, ext: str) -> str:
    stem = Path(fixture).stem
    # Filenames like "<stem>--<slug>.<ext>" — the double-dash separator makes
    # the combo identifier easy to grep without colliding with normal stem
    # punctuation.
    return f'{stem}--{slug}.{ext}'


def _generate_one(
    fixture: Path, slug: str, kwargs: dict[str, Any], ext: str, out_dir: Path
) -> Path | None:
    """Generate one snapshot. Returns the produced path or None on failure."""
    try:
        suffix = f'--{slug}'
        images_to_pics(
            [str(fixture)],
            directory=str(out_dir),
            suffix=suffix,
            extension=ext,
            **kwargs,
        )
    except Exception as exc:
        print(f'  FAIL {fixture.name} + {slug}: {type(exc).__name__}: {exc}')
        return None

    expected = out_dir / _safe_name(fixture.name, slug, ext)
    if not expected.exists():
        print(f'  MISSING {fixture.name} + {slug}: expected {expected.name}')
        return None
    return expected


def main() -> int:
    EXPECTED.mkdir(parents=True, exist_ok=True)

    survivors: list[tuple[str, str, str]] = []
    for fixture_name in ALL_FIXTURES:
        fixture = FIXTURES / fixture_name
        for slug, kwargs, ext in COMBOS:
            path = _generate_one(fixture, slug, kwargs, ext, EXPECTED)
            if path is not None:
                survivors.append((fixture_name, slug, ext))
                print(f'  ok {path.name}')

    # Emit a Python literal so test_snapshots.py can parametrize over the
    # actual produced fixtures *and* look up the kwargs for each slug. The
    # index lives next to test_snapshots.py (under tests/, not
    # tests/fixture_recipes/) so the test's `from snapshots_index import ...`
    # resolves without sys.path gymnastics. Emitting `KWARGS_BY_SLUG` here
    # makes COMBOS the single source of truth — test_snapshots no longer
    # hand-mirrors the mapping.
    formatted_snapshots = ',\n    '.join(repr(t) for t in survivors)
    kwargs_items = ',\n    '.join(
        f'{slug!r}: {kwargs!r}' for slug, kwargs, _ext in COMBOS
    )
    SNAPSHOTS_INDEX.write_text(
        '"""AUTO-GENERATED by tests/fixture_recipes/generate_snapshots.py. '
        'Do not edit by hand."""\n'
        '\n'
        'SNAPSHOTS = [\n'
        f'    {formatted_snapshots},\n'
        ']\n'
        '\n'
        'KWARGS_BY_SLUG = {\n'
        f'    {kwargs_items},\n'
        '}\n'
    )
    print(f'\nemitted {SNAPSHOTS_INDEX.name} with {len(survivors)} entries')
    return 0


if __name__ == '__main__':
    sys.exit(main())
